version: '3'
services:
  gateway:
    image: nginx:stable-alpine3.17
    ports:
      - 8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
  node_1:
    image: miner-app
    volumes:
      - ./miners.txt:/app/miners.txt:ro
  node_2:
    image: miner-app
    volumes:
      - ./miners.txt:/app/miners.txt:ro
  node_3:
    image: miner-app
    volumes:
      - ./miners.txt:/app/miners.txt:ro
